In [ ]:
# moments calculation functions
import numpy as np
import scipy.stats as st
from scipy.special import gamma
import scipy.integrate as inte
import sympy as sym
import random as rand


class Particle:
  def __init__(weight, position, velocity):
    self.weight = weight

class Population:
  def __init__(listOfParticles)
    self.population = listOfParticles

def zeroOrderMoment(population):
  # population = list[particle]
  return np.sum(population.zeroOrderMoment())

def mom_order0(L):
    # calculates zeroth order moment as observed from set L
    mom0 = 0
    for p in L:
        mom0 = mom0 + p[6]
    return mom0

def mom_order1(L):
    # calculates first order moment as observed from set L
    weights = L[:,6]
    positions = L[:,0:3]
    velicities = L[:,3:6]
    mom1 = np.zeros(3)
    for w, p, v in zip(weights, positions, velocities):

    for p in L:
        mom1[0] = mom1[0] + p[6]*p[3]
        mom1[1] = mom1[1] + p[6]*p[4]
        mom1[2] = mom1[2] + p[6]*p[5]
    return mom1

def mom_order2(L):
    # calculates second order moment as observed from set L
    mom2 = np.zeros((3,3))
    u = mom_order1(L)/mom_order0(L)
    ux, uy, uz = u[0], u[1], u[2]
    for p in L:
        mom2[0,0] = mom2[0,0] + p[6]*(p[3] - ux)*(p[3] - ux)
        mom2[0,1] = mom2[0,1] + p[6]*(p[3] - ux)*(p[4] - uy)
        mom2[0,2] = mom2[0,2] + p[6]*(p[3] - ux)*(p[5] - uz)
        mom2[1,1] = mom2[1,1] + p[6]*(p[4] - uy)*(p[4] - uy)
        mom2[1,2] = mom2[1,2] + p[6]*(p[4] - uy)*(p[5] - uz)
        mom2[2,2] = mom2[2,2] + p[6]*(p[5] - uz)*(p[5] - uz)

    mom2[1,0] = mom2[0,1]
    mom2[2,0] = mom2[0,2]
    mom2[2,1] = mom2[1,2]
    return mom2

def mom_order3(L):
    # calculates third order moment as observed from set L
    mom2 = np.zeros((3,3,3))
    u = mom_order1(L)/mom_order0(L)
    ux, uy, uz = u[0], u[1], u[2]
    for p in L:
        mom2[0,0,0] = mom2[0,0,0] + p[6]*(p[3] - ux)*(p[3] - ux)*(p[3] - ux)
        mom2[1,1,1] = mom2[1,1,1] + p[6]*(p[4] - uy)*(p[4] - uy)*(p[4] - uy)
        mom2[0,0,1] = mom2[0,0,1] + p[6]*(p[3] - ux)*(p[4] - uy)*(p[3] - ux)
        mom2[0,0,2] = mom2[0,0,2] + p[6]*(p[3] - ux)*(p[5] - uz)*(p[3] - ux)
        mom2[0,1,1] = mom2[0,1,1] + p[6]*(p[3] - ux)*(p[4] - uy)*(p[4] - uy)
        mom2[0,1,2] = mom2[0,1,2] + p[6]*(p[4] - uy)*(p[5] - uz)*(p[3] - ux)
        mom2[2,0,2] = mom2[2,0,2] + p[6]*(p[5] - uz)*(p[5] - uz)*(p[3] - ux)
        mom2[1,1,2] = mom2[1,1,2] + p[6]*(p[4] - uy)*(p[4] - uy)*(p[5] - uz)
        mom2[2,1,2] = mom2[2,1,2] + p[6]*(p[5] - uz)*(p[5] - uz)*(p[4] - uy)
        mom2[2,2,2] = mom2[2,2,2] + p[6]*(p[5] - uz)*(p[5] - uz)*(p[5] - uz)

    mom2[0,1,0] = mom2[0,0,1]
    mom2[1,0,0] = mom2[0,0,1]
    mom2[0,2,0] = mom2[0,0,2]
    mom2[2,0,0] = mom2[0,0,2]
    mom2[1,0,1] = mom2[0,1,1]
    mom2[1,1,0] = mom2[0,1,1]
    mom2[1,0,2] = mom2[0,1,2]
    mom2[1,2,0] = mom2[0,1,2]
    mom2[0,2,1] = mom2[0,1,2]
    mom2[2,0,1] = mom2[0,1,2]
    mom2[2,1,0] = mom2[0,1,2]
    mom2[2,2,0] = mom2[2,0,2]
    mom2[0,2,2] = mom2[2,0,2]
    mom2[1,2,1] = mom2[1,1,2]
    mom2[2,1,1] = mom2[1,1,2]
    mom2[2,2,1] = mom2[2,1,2]
    mom2[1,2,2] = mom2[2,1,2]
    return mom2


In [ ]:
def standard_dev(L):
    # calculate standard deviation of a set L
    av = np.zeros(len(L))+np.mean(L)
    L = np.array(L)
    S_2 = np.sum((L-av)**2)/(len(L) - 1)
    return np.sqrt(S_2)

def moments_calc(cells):
    # calculates moments of order zero to three returning a dictionary with the moments, the mean,
    # the range, the standard deviation and the coefficient of variation for each set in a given set of sets
    moments0 = []
    moments1 = []
    moments2 = []
    moments3 = []

    for c in cells:
        moments0.append(mom_order0(c))
        moments1.append(mom_order1(c))
        moments2.append(mom_order2(c))
        moments3.append(mom_order3(c))

    M0 = {'moments' : moments0,
          'mean' : np.mean(moments0),
          'range' : (min(moments0), max(moments0)),
          'st_dev' : standard_dev(moments0),
          'c_var' : standard_dev(moments0)/np.mean(moments0) * 100
         }

    moments1 = np.array(moments1)
    M1mean = np.array([np.mean(moments1[:,0]), np.mean(moments1[:,1]), np.mean(moments1[:,2])])
    M1st = np.array([standard_dev(moments1[:,0]),standard_dev(moments1[:,1]),standard_dev(moments1[:,2])])

    M1 = {'moments' : moments1,
          'mean' : M1mean,
          'range' : np.array([(min(moments1[:,0]), max(moments1[:,0])),
                             (min(moments1[:,1]), max(moments1[:,1])),
                             (min(moments1[:,2]), max(moments1[:,2]))]),
          'st_dev' : M1st,
          'c_var' :  (M1st/M1mean) * 100
         }

    moments2 = np.array(moments2)
    M2mean = np.array([(np.mean(moments2[:,0,0]),np.mean(moments2[:,0,1]), np.mean(moments2[:,0,2])),
                       (np.mean(moments2[:,1,0]),np.mean(moments2[:,1,1]), np.mean(moments2[:,1,2])),
                       (np.mean(moments2[:,2,0]),np.mean(moments2[:,2,1]), np.mean(moments2[:,2,2]))])
    M2st = np.array([(standard_dev(moments2[:,0,0]),standard_dev(moments2[:,0,1]),standard_dev(moments2[:,0,2])),
                     (standard_dev(moments2[:,1,0]),standard_dev(moments2[:,1,1]),standard_dev(moments2[:,1,2])),
                     (standard_dev(moments2[:,2,0]),standard_dev(moments2[:,2,1]),standard_dev(moments2[:,2,2]))])

    M2 = {'moments' : moments2,
          'mean' : M2mean,
          'range' : np.array([((min(moments2[:,0,0]), max(moments2[:,0,0])),
                             (min(moments2[:,0,1]), max(moments2[:,0,1])),
                             (min(moments2[:,0,2]), max(moments2[:,0,2]))),
                            ((min(moments2[:,1,0]), max(moments2[:,1,0])),
                             (min(moments2[:,1,1]), max(moments2[:,1,1])),
                             (min(moments2[:,1,2]), max(moments2[:,1,2]))),
                            ((min(moments2[:,2,0]), max(moments2[:,2,0])),
                             (min(moments2[:,2,1]), max(moments2[:,2,1])),
                             (min(moments2[:,2,2]), max(moments2[:,2,2])))]),
          'st_dev' : M2st,
          'c_var' :  (M2st/M2mean) * 100
         }

    moments3 = np.array(moments3)

    M3mean = np.array([((np.mean(moments3[:,0,0,0]),np.mean(moments3[:,0,1,0]), np.mean(moments3[:,0,2,0])),
                       (np.mean(moments3[:,1,0,0]),np.mean(moments3[:,1,1,0]), np.mean(moments3[:,1,2,0])),
                       (np.mean(moments3[:,2,0,0]),np.mean(moments3[:,2,1,0]), np.mean(moments3[:,2,2,0]))),
                       ((np.mean(moments3[:,0,0,1]),np.mean(moments3[:,0,1,1]), np.mean(moments3[:,0,2,1])),
                       (np.mean(moments3[:,1,0,1]),np.mean(moments3[:,1,1,1]), np.mean(moments3[:,1,2,1])),
                       (np.mean(moments3[:,2,0,1]),np.mean(moments3[:,2,1,1]), np.mean(moments3[:,2,2,1]))),
                       ((np.mean(moments3[:,0,0,2]),np.mean(moments3[:,0,1,2]), np.mean(moments3[:,0,2,2])),
                       (np.mean(moments3[:,1,0,2]),np.mean(moments3[:,1,1,2]), np.mean(moments3[:,1,2,2])),
                       (np.mean(moments3[:,2,0,2]),np.mean(moments3[:,2,1,2]), np.mean(moments3[:,2,2,2])))])

    M3st = np.array([((standard_dev(moments3[:,0,0,0]),standard_dev(moments3[:,0,1,0]),standard_dev(moments3[:,0,2,0])),
                     (standard_dev(moments3[:,1,0,0]),standard_dev(moments3[:,1,1,0]),standard_dev(moments3[:,1,2,0])),
                     (standard_dev(moments3[:,2,0,0]),standard_dev(moments3[:,2,1,0]),standard_dev(moments3[:,2,2,0]))),
                     ((standard_dev(moments3[:,0,0,1]),standard_dev(moments3[:,0,1,1]),standard_dev(moments3[:,0,2,1])),
                     (standard_dev(moments3[:,1,0,1]),standard_dev(moments3[:,1,1,1]),standard_dev(moments3[:,1,2,1])),
                     (standard_dev(moments3[:,2,0,1]),standard_dev(moments3[:,2,1,1]),standard_dev(moments3[:,2,2,1]))),
                     ((standard_dev(moments3[:,0,0,2]),standard_dev(moments3[:,0,1,2]),standard_dev(moments3[:,0,2,2])),
                     (standard_dev(moments3[:,1,0,2]),standard_dev(moments3[:,1,1,2]),standard_dev(moments3[:,1,2,2])),
                     (standard_dev(moments3[:,2,0,2]),standard_dev(moments3[:,2,1,2]),standard_dev(moments3[:,2,2,2])))])

    m3range = np.array([(((min(moments3[:,0,0,0]), max(moments3[:,0,0,0])),(min(moments3[:,0,1,0]), max(moments3[:,0,1,0])),
                        (min(moments3[:,0,2,0]), max(moments3[:,0,2,0]))),((min(moments3[:,1,0,0]), max(moments3[:,1,0,0])),
                        (min(moments3[:,1,1,0]), max(moments3[:,1,1,0])),(min(moments3[:,1,2,0]), max(moments3[:,1,2,0]))),
                        ((min(moments3[:,2,0,0]), max(moments3[:,2,0,0])),(min(moments3[:,2,1,0]), max(moments3[:,2,1,0])),
                        (min(moments3[:,2,2,0]), max(moments3[:,2,2,0])))),(((min(moments3[:,0,0,1]), max(moments3[:,0,0,1])),(min(moments3[:,0,1,0]), max(moments3[:,0,1,0])),
                        (min(moments3[:,0,2,1]), max(moments3[:,0,2,1]))),((min(moments3[:,1,0,1]), max(moments3[:,1,0,1])),
                        (min(moments3[:,1,1,1]), max(moments3[:,1,1,1])),(min(moments3[:,1,2,1]), max(moments3[:,1,2,1]))),
                        ((min(moments3[:,2,0,1]), max(moments3[:,2,0,1])),(min(moments3[:,2,1,1]), max(moments3[:,2,1,1])),
                        (min(moments3[:,2,2,1]), max(moments3[:,2,2,1])))),(((min(moments3[:,0,0,1]), max(moments3[:,0,0,1])),(min(moments3[:,0,1,0]), max(moments3[:,0,1,0])),
                        (min(moments3[:,0,2,1]), max(moments3[:,0,2,1]))),((min(moments3[:,1,0,1]), max(moments3[:,1,0,1])),
                        (min(moments3[:,1,1,1]), max(moments3[:,1,1,1])),(min(moments3[:,1,2,1]), max(moments3[:,1,2,1]))),
                        ((min(moments3[:,2,0,1]), max(moments3[:,2,0,1])),(min(moments3[:,2,1,1]), max(moments3[:,2,1,1])),
                        (min(moments3[:,2,2,1]), max(moments3[:,2,2,1])))) ])

    M3 = {'moments' : moments3,
          'mean' : M3mean,
          'range' : m3range,
          'st_dev' : M3st,
          'c_var' :  (M3st/M3mean) * 100
         }

    return M0, M1, M2, M3

In [ ]:
# classifying the particles
def quad_finder(L):
    # divides a given set of particles in the 8 quadrants of the velocity distribution
    Q1 = []
    Q2 = []
    Q3 = []
    Q4 = []
    Q5 = []
    Q6 = []
    Q7 = []
    Q8 = []

    for p in L:
        if p[5] >= 0:
            if p[3] >= 0:
                if p[4] >= 0:
                    Q1.append(list(p))
                else:
                    Q2.append(list(p))
            else:
                if p[4] < 0:
                    Q3.append(list(p))
                else:
                    Q4.append(list(p))
        else:
            if p[3] >= 0:
                if p[4] >= 0:
                    Q5.append(list(p))
                else:
                    Q6.append(list(p))
            else:
                if p[4] < 0:
                    Q7.append(list(p))
                else:
                    Q8.append(list(p))

    return [Q1, Q2,  Q3, Q4, Q5, Q6, Q7, Q8]

def clust_finder1(n, L): # bad method
    '''
    n - size of clusters
    L - set of particles to find cluster in
    '''
    # given a set of particles it returns clusters on n particles for each quadrant
    # selected as described in the overleaf document, it also select two clusters,
    # with the least and most overall weight and returns them as well

    def sort_v(Q):
        # return a sorted list of the largest overall velocities (adding absolute values for each direction)
        list_v = []
        for p in Q:
            list_v.append(abs(p[3])+ abs(p[4])+ abs(p[5]))
        llist = sorted(list_v)
        return list(list_v)

    def sort_r(Q):
        # return a sorted list of the largest overall distance form the bottom left corner of the cell
        list_r = []
        for p in Q:
            list_r.append(abs(p[0])+ abs(p[1])+ abs(p[2]))
        llist = sorted(list_r)
        return list(llist)

    quadrants = quad_finder(L)

    clusters = []

    for Q in quadrants:

        if len(Q) > n:
            LV = sort_v(Q) # sorted list of overall velocity
            RV = sort_r(Q) # sorted list of overall distance

            def dist_v(p):
                i = LV.index(abs(p[3]) + abs(p[4]) + abs(p[5]))
                if i < len(LV) -n+1:
                    return LV[i+n-1] - LV[i]
                elif i >= len(LV) -n+1:
                    return np.exp(100)

            def dist_r(p):
                i = RV.index(abs(p[0]) + abs(p[1]) + abs(p[2]))
                if i < len(RV) -n+1:
                    return RV[i+n-1] - RV[i]
                elif i >= len(LV) -n+1:
                    return np.exp(100)

            VQ = sorted(Q, key = dist_v) # sort Q with respect to the first distance defined
            RQ = sorted(Q, key = dist_r) # sort Q with respect to the second distance defined

            def rank(p): # we define the rank as the sum of the position of a particle
                         # with respect to the first and second distances defined
               return VQ.index(p) +  RQ.index(p)

            Q.sort(key = rank) # sort Q with respect to rank

            clusters.append(Q[0:n])

        elif len(Q) == n:
            # if Q is already of size n append the whole of Q
            clusters.append(Q)

    lightest = np.array(clusters[0])
    for c in clusters:
        wl = np.sum(lightest[:,6])
        c = np.array(c)
        w = np.sum(c[:,6])
        if wl > w:
            lightest = c

    heaviest = np.array(clusters[0])
    for c in clusters:
        wl = np.sum(lightest[:,6])
        c = np.array(c)
        w = np.sum(c[:,6])
        if wl < w:
            heaviest = c

    return clusters, lightest, heaviest


def clust_finder2(n, L):
    '''
    n - size of clusters
    L - set of particles to find cluster in
    '''
    quadrants = quad_finder(L)

    clusters = []

    for Q in quadrants:

        if len(Q) > n:

            def dist_v_par(p):
                return (abs(p[3]) + abs(p[4]) + abs(p[5]))

            def dist_r_par(p):
                return (abs(p[0]) + abs(p[1]) + abs(p[2]))

            def dist_v_clus(c):
                return dist_v_par(c[n-1]) - dist_v_par(c[0])

            def dist_r_clus(c):
                return dist_r_par(c[0][n-1]) - dist_r_par(c[0][0])


            LV = sorted(Q, key = dist_v_par )

            LVc =[]

            for i in range(0, len(LV)):
                if i+n <= len(LV):
                    LVc.append(np.array(LV)[i:i+n])
                else:
                    LVc.append(np.array(LV)[-n:])

            clusV = sorted(LVc, key = dist_v_clus)

            clusR = sorted(LVc, key = dist_v_clus)

            def rank(c):
                for i in range(0,len(clusV)):
                    if np.array_equal(c, clusV[i]):
                        rV = i
                for i in range(0,len(clusR)):
                    if np.array_equal(c, clusR[i]):
                        rR = i
                return rV + rR

            LVc.sort(key = rank)

            clusters.append(LVc[0])

        elif len(Q) == n:
            # if Q is already of size n append the whole of Q
            clusters.append(Q)

    lightest = np.array(clusters[0])
    for c in clusters:
        wl = np.sum(lightest[:,6])
        c = np.array(c)
        w = np.sum(c[:,6])
        if wl > w:
            lightest = c

    heaviest = np.array(clusters[0])
    for c in clusters:
        wl = np.sum(lightest[:,6])
        c = np.array(c)
        w = np.sum(c[:,6])
        if wl < w:
            heaviest = c

    clusters.sort(key = dist_v_clus)

    return clusters, lightest, heaviest


In [ ]:
def ran_cells_M(n, m, l, s, g1):
    '''
    n - number of sets of particles
    m - size of set of particles
    l - loc parameter
    s - scale parameter
    g1 - lowesdst corner
    Maxwellian distribution
    '''
    cells = []

    for i in range(0,n):
        L = np.zeros((m, 7))
        L[:,0] = np.random.uniform(g1[0], g1[0] + 1.0, size=m).reshape(1,m)
        L[:,1] = np.random.uniform(g1[1], g1[1] +  1.0, size=m).reshape(1,m)
        L[:,2] = np.random.uniform(g1[2], g1[2] + 1.0, size=m).reshape(1,m)
        L[:,3] = np.random.normal(loc= l, scale= s, size=m).reshape(1,m)
        L[:,4] = np.random.normal(loc= l, scale= s, size=m).reshape(1,m)
        L[:,5] = np.random.normal(loc= l, scale= s, size=m).reshape(1,m)
        L[:,6] = np.random.uniform(0,  1.0, size=m).reshape(1,m)
        cells.append(L)

    return cells

def ran_cells_DM(n, m, l1, s1, l2, s2, g1):
    '''
    n - number of sets of particles
    m - size of set of particles
    l1 - loc parameter first maxwellian
    s1 - scale parameter first maxwellian
    l2 - loc parameter second maxwellian
    s2 - scale parameter second maxwellian
    g1 - lowesdst corner
    Double Maxwellian distribution
    '''
    cells = []

    for i in range(0,n):
        L = np.zeros((m, 7))
        L[:,0] = np.random.uniform(g1[0], g1[0] + 1.0, size=m).reshape(1,m)
        L[:,1] = np.random.uniform(g1[1], g1[1] +  1.0, size=m).reshape(1,m)
        L[:,2] = np.random.uniform(g1[2], g1[2] + 1.0, size=m).reshape(1,m)
        L[:,3] = (1/2)*(np.random.normal(loc= l1, scale= s1, size=m).reshape(1,m) + np.random.normal(loc= l2, scale= s2, size=m).reshape(1,m))
        L[:,4] = (1/2)*(np.random.normal(loc= l1, scale= s1, size=m).reshape(1,m) + np.random.normal(loc= l2, scale= s2, size=m).reshape(1,m))
        L[:,5] = (1/2)*(np.random.normal(loc= l1, scale= s1, size=m).reshape(1,m) + np.random.normal(loc= l2, scale= s2, size=m).reshape(1,m))
        L[:,6] = np.random.uniform(0,  1.0, size=m).reshape(1,m)
        cells.append(L)

    return cells

def kappa_pdf(k, v, w):
    f = lambda v : ((1 + v**2/(k * (w**2)))**(-(k+1)))
    N = inte.quad(f, -100, 100)[0]
    return (1/N)*((1 + v**2/(k * (w**2)))**(-(k+1)))

def rejection_sampling(n, D, R, pdf):
    '''
    n - number of observations required
    D - domain of distribution function
    R - range of distribution function
    pdf - probability distribution function
    '''
    observations = []
    lx, ux = D
    ly, uy = R
    counter = 0
    while len(observations) < n:
        x = np.random.uniform(lx, ux)
        y = np.random.uniform(ly, uy)
        if y < pdf(x):
            observations.append(x)

        counter = counter + 1
        if counter > 100*n**n:
            return print('Error')
    return observations

def ran_cells_K_rej(n, m, k, w, g1):
    '''
    n - number of sets of particles
    m - size of set of particles
    k - kappa parameter
    w - heat width
    g1 - lowest corner
    Kappa distribution
    '''
    cells = []

    R = (0, kappa_pdf(k, 0, w))
    D = (-0.1/k, 0.1/k)

    f = lambda v : ((1 + v**2/(k * (w**2)))**(-(k+1)))
    N = inte.quad(f, -100, 100)[0]

    def pdf(v):
        return (1/N)*((1 + v**2/(k * (w**2)))**(-(k+1)))

    for i in range(0,n):
        L = np.zeros((m, 7))
        L[:,0] = np.random.uniform(g1[0], g1[0] + 1.0, size=m).reshape(1,m)
        L[:,1] = np.random.uniform(g1[1], g1[1] +  1.0, size=m).reshape(1,m)
        L[:,2] = np.random.uniform(g1[2], g1[2] + 1.0, size=m).reshape(1,m)
        L[:,3] = rejection_sampling(m, D, R, pdf)
        L[:,4] = rejection_sampling(m, D, R, pdf)
        L[:,5] = rejection_sampling(m, D, R, pdf)
        L[:,6] = np.random.uniform(0, 1.0, size=m).reshape(1,m)
        cells.append(L)

    return cells

def ran_cells_3U(n, m, lx, ux, ly, uy, lz, uz, g1):
    '''
    n - number of sets of particles
    m - size of eqch set
    lx - lower bound x
    ux - upper bound x
    ly - lower bound y
    uy - upper bound y
    lz - lower bound z
    uz - upper bound z
    g1 - lowest corner
    3 unequal uniform distribution
    '''
    cells = []

    for i in range(0,n):
        L = np.zeros((m, 7))
        L[:,0] = np.random.uniform(g1[0], g1[0] + 1.0, size=m).reshape(1,m)
        L[:,1] = np.random.uniform(g1[1], g1[1] +  1.0, size=m).reshape(1,m)
        L[:,2] = np.random.uniform(g1[2], g1[2] + 1.0, size=m).reshape(1,m)
        L[:,3] = np.random.uniform(lx, ux, size=m).reshape(1,m)
        L[:,4] = np.random.uniform(ly, uy, size=m).reshape(1,m)
        L[:,5] = np.random.uniform(lz, uz, size=m).reshape(1,m)
        L[:,6] = np.random.uniform(0,  1.0, size=m).reshape(1,m)
        cells.append(L)

    return cells

In [ ]:
def continuous_moments(f, n):
    '''
    f - distribution function
    n - number of particles per cell (weights assumed to be from U(0,1)
    note :  space distribution assumed to be uniform
    '''
    moment0 = (inte.quad(f, -100, 100)[0]**3)*n/2

    fx = lambda v : f(v)*v

    fx2 = lambda v : f(v)*((v-(moment1_1/moment0))**2)

    fx21 = lambda v : f(v)*(v-(moment1_1/moment0))

    moment1_1 = (inte.quad(fx, -100, 100)[0]*(inte.quad(f, -100, 100)[0]**2))*n/2

    moment1 = np.zeros(3) + moment1_1

    moment2_2 = (inte.quad(fx2, -100, 100)[0]*(inte.quad(f, -100, 100)[0]**2))*n/2

    moment2_1 = ((inte.quad(fx21, -100, 100)[0]**2)*inte.quad(f, -100, 100)[0])*n/2

    moment2 = np.array([(moment2_2,moment2_1,moment2_1),(moment2_1,moment2_2,moment2_1),(moment2_1,moment2_1,moment2_2)])
    return moment0, moment1, moment2


def kappa_for_int(w,k):
    f = lambda v : ((1 + v**2/(k * (w**2)))**(-(k+1)))
    N = inte.quad(f, -100, 100)[0]
    return lambda v : (1/N) * ((1 + v**2/(k * (w**2)))**(-(k+1)))

def norm_for_int(mu, sig):
    return lambda x : (1/np.sqrt(2*np.pi*sig**2))*np.exp(-((x-mu)**2)/(2*sig**2))

def d_norm_for_int(mu1, sig1, mu2, sig2):
    return lambda x : (1/2)*((1/np.sqrt(2*np.pi*sig1**2))*np.exp(-((x-mu1)**2)/(2*sig1**2)) + (1/np.sqrt(2*np.pi*sig2**2))*np.exp(-((x-mu2)**2)/(2*sig2**2)))

f_k1 = kappa_for_int(1, 5)
f_n = norm_for_int(0, 1)
f_dn1 = d_norm_for_int(-0.5, 1, 0.5, 1)
f_dn2 = d_norm_for_int( 0, 0.1, 0, 3)


c_nor1_M0, c_nor1_M1, c_nor1_M2 = continuous_moments(f_n, 100)
c_dnor1_M0, c_dnor1_M1, c_dnor1_M2 = continuous_moments(f_dn1, 100)
c_dnor2_M0, c_dnor2_M1, c_dnor2_M2 = continuous_moments(f_dn2, 100)
c_kappa1_M0, c_kappa1_M1, c_kappa1_M2 = continuous_moments(f_k1, 100)


print(f"normal {c_nor1_M0, c_nor1_M1}")
print(f"{c_nor1_M2}")
print(f"d normal 1 {c_dnor1_M0, c_dnor1_M1}")
print(f"{c_dnor1_M2}")
print(f"d normal 2 {c_dnor2_M0, c_dnor2_M1}")
print(f"{c_dnor2_M2}")
print(f"Kappa {c_kappa1_M0, c_kappa1_M1}")
print(f"{c_kappa1_M2}")

normal (50.000000000000036, array([0., 0., 0.]))
[[50.  0.  0.]
 [ 0. 50.  0.]
 [ 0.  0. 50.]]
d normal 1 (50.000000000000036, array([0., 0., 0.]))
[[62.5  0.   0. ]
 [ 0.  62.5  0. ]
 [ 0.   0.  62.5]]
d normal 2 (50.0, array([0., 0., 0.]))
[[225.25   0.     0.  ]
 [  0.   225.25   0.  ]
 [  0.     0.   225.25]]
Kappa (49.999999999999986, array([0., 0., 0.]))
[[27.77777778  0.          0.        ]
 [ 0.         27.77777778  0.        ]
 [ 0.          0.         27.77777778]]


In [ ]:
stan_nor1 = ran_cells_M(100, 100, 0, 1, (0,0,0))
nor1_M0, nor1_M1, nor1_M2, nor1_M3 = moments_calc(stan_nor1)

d_nor1 = ran_cells_DM(100, 100, -0.5, 1, 0.5, 1, (0,0,0))
dnor1_M0, dnor1_M1, dnor1_M2, dnor1_M3 = moments_calc(d_nor1)

d_nor2 = ran_cells_DM(100, 100, 0, 0.1, 0, 3, (0,0,0))
dnor2_M0, dnor2_M1, dnor2_M2, dnor2_M3 = moments_calc(d_nor2)

kappa1 = ran_cells_K_rej(100, 100, 5, 1, (0,0,0))
kappa1_M0, kappa1_M1, kappa1_M2, kappa1_M3 = moments_calc(kappa1)

In [ ]:
Nnor_m0_D = 2*(c_nor1_M0 - nor1_M0['mean'])/(nor1_M0['st_dev']**2)
Nnor_m1_D = 2*(c_nor1_M1 - nor1_M1['mean'])/(np.mean(nor1_M1['st_dev']**2))
Nnor_m2_D = 2*(c_nor1_M2 - nor1_M2['mean'])/(np.mean(nor1_M1['st_dev']**2))

Ndnor1_m0_D = 2*(c_dnor1_M0 - dnor1_M0['mean'])/(dnor1_M0['st_dev']**2)
Ndnor1_m1_D = 2*(c_dnor1_M1 - dnor1_M1['mean'])/(np.mean(dnor1_M1['st_dev']**2))
Ndnor1_m2_D = 2*(c_dnor1_M2 - dnor1_M2['mean'])/(np.mean(dnor1_M2['st_dev']**2))

Ndnor2_m0_D = 2*(c_dnor2_M0 - dnor2_M0['mean'])/(dnor2_M0['st_dev']**2)
Ndnor2_m1_D = 2*(c_dnor2_M1 - dnor2_M1['mean'])/(np.mean(dnor2_M1['st_dev']**2))
Ndnor2_m2_D = 2*(c_dnor2_M2 - dnor2_M2['mean'])/(np.mean(dnor2_M2['st_dev']**2))

Nkappa1_m0_D = 2*(c_kappa1_M0 - kappa1_M0['mean'])/(kappa1_M0['st_dev']**2)
Nkappa1_m1_D = 2*(c_kappa1_M1 - kappa1_M1['mean'])/(np.mean(kappa1_M1['st_dev']**2))
Nkappa1_m2_D = 2*(c_kappa1_M2 - kappa1_M2['mean'])/(np.mean(kappa1_M2['st_dev']**2))

nor_m0_D = (c_nor1_M0 - nor1_M0['mean'])
nor_m1_D = (c_nor1_M1 - nor1_M1['mean'])
nor_m2_D = (c_nor1_M2 - nor1_M2['mean'])

dnor1_m0_D = (c_dnor1_M0 - dnor1_M0['mean'])
dnor1_m1_D = (c_dnor1_M1 - dnor1_M1['mean'])
dnor1_m2_D = (c_dnor1_M2 - dnor1_M2['mean'])

dnor2_m0_D = (c_dnor2_M0 - dnor2_M0['mean'])
dnor2_m1_D = (c_dnor2_M1 - dnor2_M1['mean'])
dnor2_m2_D = (c_dnor2_M2 - dnor2_M2['mean'])

kappa1_m0_D = (c_kappa1_M0 - kappa1_M0['mean'])
kappa1_m1_D = (c_kappa1_M1 - kappa1_M1['mean'])
kappa1_m2_D = (c_kappa1_M2 - kappa1_M2['mean'])

nor_m0_D, nor_m1_D, nor_m2_D, Nnor_m0_D, Nnor_m1_D, Nnor_m2_D

(np.float64(0.21992943311414592),
 array([-0.38013287,  0.26171056,  0.14977634]),
 array([[ 0.39659039, -0.32714837, -0.02472274],
        [-0.32714837, -0.44517135,  0.42696043],
        [-0.02472274,  0.42696043,  2.45828893]]),
 np.float64(0.04430847254757881),
 array([-0.01963525,  0.0135183 ,  0.00773649]),
 array([[ 0.02048534, -0.0168984 , -0.00127702],
        [-0.0168984 , -0.02299472,  0.02205406],
        [-0.00127702,  0.02205406,  0.12697957]]))

In [ ]:
dnor1_m0_D, dnor1_m1_D, dnor1_m2_D, Ndnor1_m0_D, Ndnor1_m1_D, Ndnor1_m2_D

(np.float64(-0.4280218362437225),
 array([-0.1570709 ,  0.11029753, -0.47985739]),
 array([[36.93101946, -0.50463537, -0.15728641],
        [-0.50463537, 38.03402486,  0.05854606],
        [-0.15728641,  0.05854606, 37.62921988]]),
 np.float64(-0.11329765726271707),
 array([-0.01766292,  0.01240317, -0.05396087]),
 array([[ 6.19798066, -0.08469087, -0.02639673],
        [-0.08469087,  6.38309351,  0.00982554],
        [-0.02639673,  0.00982554,  6.31515676]]))

In [ ]:
dnor2_m0_D, dnor2_m1_D, dnor2_m2_D, Ndnor2_m0_D, Ndnor2_m1_D, Ndnor2_m2_D

(np.float64(-0.13007319630748526),
 array([-1.48613952, -1.51519511,  0.29869356]),
 array([[ 1.13980643e+02,  1.74891963e+00,  1.61752655e+00],
        [ 1.74891963e+00,  1.17035276e+02, -9.37852247e-02],
        [ 1.61752655e+00, -9.37852247e-02,  1.14398758e+02]]),
 np.float64(-0.03203912494523332),
 array([-0.03851342, -0.0392664 ,  0.00774067]),
 array([[ 9.91270076e-01,  1.52100536e-02,  1.40673505e-02],
        [ 1.52100536e-02,  1.01783569e+00, -8.15633991e-04],
        [ 1.40673505e-02, -8.15633991e-04,  9.94906353e-01]]))

In [ ]:
kappa1_m0_D, kappa1_m1_D, kappa1_m2_D, Nkappa1_m0_D, Nkappa1_m1_D, Nkappa1_m2_D

(np.float64(-0.4615343565189818),
 array([ 0.00906383, -0.00121907, -0.00649887]),
 array([[ 2.77711158e+01,  4.72037655e-08,  1.58998573e-04],
        [ 4.72037655e-08,  2.77711997e+01, -4.29705221e-05],
        [ 1.58998573e-04, -4.29705221e-05,  2.77711148e+01]]),
 np.float64(-0.1485174036557145),
 array([ 3.63265107, -0.48858364, -2.60465287]),
 array([[ 8.30862495e+07,  1.41225288e-01,  4.75695510e+02],
        [ 1.41225288e-01,  8.30865004e+07, -1.28560175e+02],
        [ 4.75695510e+02, -1.28560175e+02,  8.30862463e+07]]))

In [ ]:
# following a 3 merged into 2 structure, solving the order 0 and 1 moments
# and the diagonal of the order 2 moment since we have evidences
# that non diagonal entry are noisy, as suggested
# for the previously considered set of equations the additional equation is used
# to establish a free relation between the weights to be calibrated to the specific case

wa, wb, vax, vay, vaz, vbx, vby, vbz =  sym.symbols('wa wb vax vay vaz vbx vby vbz')

w1, w2, w3, v1x, v1y, v1z, v2x, v2y, v2z, v3x, v3y, v3z, p =  sym.symbols('w1 w2 w2 v1x v1y v1z v2x v2y v2z v3x v3y v3z p')

g1x, g1y, g1z, g2x, g2y, g2z, g3x, g3y, g3z, g4x, g4y, g4z, g5x, g5y, g5z, g6x, g6y, g6z, g7x, g7y, g7z =  sym.symbols('g1x g1y g1z g2x g2y g2z g3x g3y g3z g4x g4y g4z g5x g5y g5z g6x g6y g6z g7x g7y g7z')

r1x, r1y, r1z, r2x, r2y, r2z = sym.symbols('r1x r1y r1z r2x r2y r2z')

n, ux, uy, uz, Pxx, Pyy, Pzz = sym.symbols('n ux uy uz Pxx Pyy Pzz')

g1, g2, g3, g4, g5, g6, g7 = sym.symbols('g1 g2 g3 g4 g5 g6 g7')


eq1 = sym.Eq(n, wa+wb)

eq2 = sym.Eq(n*ux, wa*vax+wb*vbx)

eq3 = sym.Eq(n*uy, wa*vay+wb*vby)

eq4 = sym.Eq(n*uz, wa*vaz+wb*vbz)

eq5 = sym.Eq(Pxx, wa*(vax - ux)*(vax - ux)+wb*(vbx - ux)*(vbx - ux))

eq6 = sym.Eq(Pyy, wa*(vay - uy)*(vay - uy)+wb*(vby - uy)*(vby - uy))

eq7 = sym.Eq(Pzz, wa*(vaz - uz)*(vaz - uz)+wb*(vbz - uz)*(vbz - uz))

eq8 = sym.Eq(wa, wb)

#eq8 = sym.Eq(g1, wa*((r1x - g1x)*(r1y - g1y)*(r1z - g1z) + wb*(r2x - g1x)*(r2y - g1y)*(r2z - g1z)))

#eq9 = sym.Eq(g2, wa*((r1x - g2x)*(r1y - g2y)*(r1z - g2z) + wb*(r2x - g2x)*(r2y - g2y)*(r2z - g2z)))

#eq10 = sym.Eq(g3, wa*((r1x - g3x)*(r1y - g3y)*(r1z - g3z) + wb*(r2x - g3x)*(r2y - g3y)*(r2z - g3z)))

#eq11 = sym.Eq(g4, wa*((r1x - g4x)*(r1y - g4y)*(r1z - g4z) + wb*(r2x - g4x)*(r2y - g4y)*(r2z - g4z)))

#eq12 = sym.Eq(g5, wa*((r1x - g5x)*(r1y - g5y)*(r1z - g5z) + wb*(r2x - g5x)*(r2y - g5y)*(r2z - g5z)))

#eq13 = sym.Eq(g6, wa*((r1x - g6x)*(r1y - g6y)*(r1z - g6z) + wb*(r2x - g6x)*(r2y - g6y)*(r2z - g6z)))

#eq14 = sym.Eq(g7, wa*((r1x - g7x)*(r1y - g7y)*(r1z - g7z) + wb*(r2x - g7x)*(r2y - g7y)*(r2z - g7z)))



solutions = sym.solve((eq1, eq2, eq3, eq4, eq5, eq6, eq7, eq8), (wa, wb, vax, vay, vaz, vbx, vby, vbz))

# note that many solutions are possible with variations in sign within the expressions
# this means that following the minimization of dispersion we can both change p and choose the
# most appropriate set of equations

In [ ]:
w1, w2, w3, v1x, v1y, v1z, v2x, v2y, v2z, v3x, v3y, v3z, p =  sym.symbols('w1 w2 w2 v1x v1y v1z v2x v2y v2z v3x v3y v3z p')

n, ux, uy, uz, Pxx, Pyy, Pzz = sym.symbols('n ux uy uz Pxx Pyy Pzz')

g1, g2, g3, g4, g5, g6, g7 = sym.symbols('g1 g2 g3 g4 g5 g6 g7')

eq1 = sym.Eq(n, wa+wb)

eq2 = sym.Eq(n*ux, wa*vax+wb*vbx)

eq3 = sym.Eq(n*uy, wa*vay+wb*vby)

eq4 = sym.Eq(n*uz, wa*vaz+wb*vbz)

eq5 = sym.Eq(Pxx, wa*(vax - ux)*(vax - ux)+wb*(vbx - ux)*(vbx - ux))

eq6 = sym.Eq(Pyy, wa*(vay - uy)*(vay - uy)+wb*(vby - uy)*(vby - uy))

eq7 = sym.Eq(Pzz, wa*(vaz - uz)*(vaz - uz)+wb*(vbz - uz)*(vbz - uz))

eq8 = sym.Eq(wa, p*wb)

solutions2 = sym.solve((eq1, eq2, eq3, eq4, eq5, eq6, eq7, eq8), (wa, wb, vax, vay, vaz, vbx, vby, vbz))

In [ ]:
# implementing a first merging algorithm based on the above equations for 3->2 merging

def merger1(L, k, g1, pos):
    '''
    L - set of pqrticles to be merged
    k - desired number of particles
    g1 - smallest grid angle (i.e. the angle of the grid with lowest added coordinates value)
    '''
    L = list(L)
    s = len(L)

    while len(L) > k:
        p1 = np.zeros(7)
        p2 = np.zeros(7)
        p1_r = np.zeros(7)
        p2_r = np.zeros(7)
        score_r = 1000

        clus = clust_finder2(3, L)[0][0]

        w1 = clus[0,6]
        v1x = clus[0,3]
        v1y = clus[0,4]
        v1z = clus[0,5]
        w2 = clus[1,6]
        v2x = clus[1,3]
        v2y = clus[1,4]
        v2z = clus[1,5]
        w3 = clus[2,6]
        v3x = clus[2,3]
        v3y = clus[2,4]
        v3z = clus[2,5]

        aux = w1*v1x+w2*v2x+w3*v3x
        auy = w1*v1y+w2*v2y+w3*v3y
        auz = w1*v1z+w2*v2z+w3*v3z
        aPxx = w1*(v1x - aux)*(v1x - aux)+w2*(v2x - aux)*(v2x - aux)
        aPxy = w1*(v1x - aux)*(v1y - auy)+w2*(v2x - aux)*(v2y - auy)
        aPxz = w1*(v1x - aux)*(v1z - auz)+w2*(v2x - aux)*(v2z - auz)
        aPyz = w1*(v1z - auz)*(v1y - auy)+w2*(v2z - auz)*(v2y - auy)
        aPzz = w1*(v1z - auz)*(v1z - auz)+w2*(v2z - auz)*(v2z - auz)
        aPyy = w1*(v1y - auy)*(v1y - auy)+w2*(v2y - auy)*(v2y - auy)

        for sol in solutions:
            score = 0
            p1[6] = sol[0].subs(n,w1+w2)
            p2[6] = sol[1].subs(n,w1+w2)
            p1[3] = sol[2].subs([(n,w1+w2),(ux, aux), (Pxx, aPxx)])
            p1[4] = sol[3].subs([(n,w1+w2),(uy, auy), (Pyy, aPyy)])
            p1[5] = sol[4].subs([(n,w1+w2),(uz, auz), (Pzz, aPzz)])
            p2[3] = sol[5].subs([(n,w1+w2),(ux, aux), (Pxx, aPxx)])
            p2[4] = sol[6].subs([(n,w1+w2),(uy, auy), (Pyy, aPyy)])
            p2[5] = sol[7].subs([(n,w1+w2),(uz, auz), (Pzz, aPzz)])

            if abs(p1[3] + aux) != abs(p1[3]) + abs(aux):
                score = score + 1
                if abs(p1[3] + aux) >= abs(p1_r[3] + aux):
                    score = score + 1
            if abs(p1[4] + auy) != abs(p1[4]) + abs(auy):
                score = score + 1
                if abs(p1[4] + auy) >= abs(p1_r[4] + auy):
                    score = score + 1
            if abs(p1[5] + auz) != abs(p1[5]) + abs(auz):
                score = score + 1
                if abs(p1[6] + auz) >= abs(p1_r[6] + auz):
                    score = score + 1
            if abs(p2[3] + aux) != abs(p2[3]) + abs(aux):
                score = score + 1
                if abs(p2[3] + aux) >= abs(p2_r[3] + aux):
                    score = score + 1
            if abs(p2[4] + auy) != abs(p2[4]) + abs(auy):
                score = score + 1
                if abs(p2[4] + auy) >= abs(p2_r[4] + auy):
                    score = score + 1
            if abs(p2[5] + auz) != abs(p2[5]) + abs(auz):
                score = score + 1
                if abs(p2[6] + auz) >= abs(p2_r[6] + auz):
                    score = score + 1

            if score_r > score:
                p1_r = p1
                p2_r = p2
                score_r = score

        # methods for positioning of the particles
        if pos == 1: #first method, randomly following uniform distribution on the whole cell
            p1_r[0] = np.random.uniform(g1[0], g1[0] + 1.0)
            p1_r[1] = np.random.uniform(g1[1], g1[1] +  1.0)
            p1_r[2] = np.random.uniform(g1[2], g1[2] + 1.0)
            p2_r[0] = np.random.uniform(g1[0], g1[0] + 1.0)
            p2_r[1] = np.random.uniform(g1[1], g1[1] +  1.0)
            p2_r[2] = np.random.uniform(g1[2], g1[2] + 1.0)

        if pos == 2: #second method, randomly following uniform distribution within original particles limits
            p1_r[0] = np.random.uniform(min(clus[:,0]), max(clus[:,0]))
            p1_r[1] = np.random.uniform(min(clus[:,1]), max(clus[:,1]))
            p1_r[2] = np.random.uniform(min(clus[:,2]), max(clus[:,2]))
            p2_r[0] = np.random.uniform(min(clus[:,0]), max(clus[:,0]))
            p2_r[1] = np.random.uniform(min(clus[:,1]), max(clus[:,1]))
            p2_r[2] = np.random.uniform(min(clus[:,2]), max(clus[:,2]))

        if pos == 3: #third method, random uniform in extended particles limits
            xrange = min(max(clus[:,0]) - np.mean(clus[:,0]), np.mean(clus[:,0])- min(clus[:,0]))
            yrange = min(max(clus[:,1]) - np.mean(clus[:,1]), np.mean(clus[:,1])- min(clus[:,1]))
            zrange = min(max(clus[:,2]) - np.mean(clus[:,2]), np.mean(clus[:,2])- min(clus[:,2]))
            p1_r[0] = np.random.uniform(max(min(clus[:,0])-xrange/2, 1), min(max(clus[:,0])+xrange/2, 1))
            p1_r[1] = np.random.uniform(max(min(clus[:,1])-yrange/2, 1), min(max(clus[:,1])+yrange/2, 1))
            p1_r[2] = np.random.uniform(max(min(clus[:,2])-zrange/2, 1), min(max(clus[:,2])+zrange/2, 1))
            p2_r[0] = np.random.uniform(max(min(clus[:,0])-xrange/2, 1), min(max(clus[:,0])+xrange/2, 1))
            p2_r[1] = np.random.uniform(max(min(clus[:,1])-yrange/2, 1), min(max(clus[:,1])+yrange/2, 1))
            p2_r[2] = np.random.uniform(max(min(clus[:,2])-zrange/2, 1), min(max(clus[:,2])+zrange/2, 1))

        if pos == 4: #fourth method, randomly chosen position out of 2 of the original particles'
            first_pos = rand.randint(0,2)
            second_pos = first_pos
            while second_pos == first_pos:
                second_pos = rand.randint(0,2)
            if first_pos == 0:
                p1_r[0:3] = clus[0,0:3]
            elif first_pos == 1:
                p1_r[0:3] = clus[1,0:3]
            elif first_pos == 2:
                p1_r[0:3] = clus[2,0:3]
            if second_pos == 0:
                p2_r[0:3] = clus[0,0:3]
            elif second_pos == 1:
                p2_r[0:3] = clus[1,0:3]
            elif second_pos == 2:
                p2_r[0:3] = clus[2,0:3]

        if pos == 5: #fifth method, around weighted mean of original particles position
            avx = np.mean(max(clus[:,0])* clus[:,6])
            avy = np.mean(max(clus[:,1])* clus[:,6])
            avz = np.mean(max(clus[:,2])* clus[:,6])

            p1_r[0] = np.sum(clus[:,0]) - max(clus[:,0]) - min(clus[:,0])
            p1_r[1] = np.sum(clus[:,1]) - max(clus[:,1]) - min(clus[:,1])
            p1_r[2] = np.sum(clus[:,2]) - max(clus[:,2]) - min(clus[:,2])

            p2_r[0] = 2*avx-p1_r[0]
            p2_r[1] = 2*avy-p1_r[1]
            p2_r[2] = 2*avz-p1_r[2]

        if pos == 6: #sixth method, weighted random positions from previous particles positions
            w = np.sum(clus[:,6])
            poslist = [clus[0,0:3]] * int((clus[0,6]/w)*1000) + [clus[1,0:3]] * int((clus[1,6]/w)*1000)  + [clus[2,0:3]] * int((clus[2,6]/w)*1000)
            p1_r[0:3] = rand.choice(poslist)
            p2_r[0:3] = p1_r[0:3]
            while p2_r[0] == p1_r[0] and p2_r[1] == p1_r[1] and p2_r[2] == p1_r[2]:
                p2_r[0:3] = rand.choice(poslist)




        L = [el for el in L if not (np.array_equal(el, clus[0]) or np.array_equal(el, clus[1]) or np.array_equal(el, clus[2]))]
        L.append(p1_r)
        L.append(p2_r)

        #print(f'changes iteration {s - len(L)}')
        #print('before')
        #print(clus[0], clus[1], clus[2])
        #print('after')
        #print(p1_r, p2_r)



    return np.array(L)

In [ ]:
LM = ran_cells_M(1, 104, 0, 1, (0,0,0))[0]
LMmerg_pos1 = merger1(LM, 100, (0,0,0), 1)
LMmerg_pos2 = merger1(LM, 100, (0,0,0), 2)
LMmerg_pos3 = merger1(LM, 100, (0,0,0), 3)
LMmerg_pos4 = merger1(LM, 100, (0,0,0), 4)
LMmerg_pos5 = merger1(LM, 100, (0,0,0), 5)
LMmerg_pos6 = merger1(LM, 100, (0,0,0), 6)

merged_list = (LMmerg_pos1, LMmerg_pos2, LMmerg_pos3, LMmerg_pos4, LMmerg_pos5, LMmerg_pos6)


def moments_on_grid(L, g1):
    M0 = np.zeros(8)
    M1 = np.zeros((3,8))
    M2 = np.zeros((3,3,8))

    for p in L:
        M0[0] = M0[0] + p[6]*abs((p[0] - g1[0])*(p[1] - g1[1])*(p[2] - g1[2]))
        M0[1] = M0[1] + p[6]*abs((p[0] - g1[0])*(p[1] - g1[1]-1)*(p[2] - g1[2]))
        M0[2] = M0[2] + p[6]*abs((p[0] - g1[0]-1)*(p[1] - g1[1]-1)*(p[2] - g1[2]))
        M0[3] = M0[3] + p[6]*abs((p[0] - g1[0]-1)*(p[1] - g1[1])*(p[2] - g1[2]))
        M0[4] = M0[4] + p[6]*abs((p[0] - g1[0])*(p[1] - g1[1])*(p[2] - g1[2]-1))
        M0[5] = M0[5] + p[6]*abs((p[0] - g1[0])*(p[1] - g1[1]-1)*(p[2] - g1[2]-1))
        M0[6] = M0[6] + p[6]*abs((p[0] - g1[0]-1)*(p[1] - g1[1]-1)*(p[2] - g1[2]-1))
        M0[7] = M0[7] + p[6]*abs((p[0] - g1[0]-1)*(p[1] - g1[1])*(p[2] - g1[2]-1))

        M1[:,0] = M1[:,0] + p[6]*abs((p[0] - g1[0])*(p[1] - g1[1])*(p[2] - g1[2]))*p[0:3]
        M1[:,1] = M1[:,1] + p[6]*abs((p[0] - g1[0])*(p[1] - g1[1]-1)*(p[2] - g1[2]))*p[0:3]
        M1[:,2] = M1[:,2] + p[6]*abs((p[0] - g1[0]-1)*(p[1] - g1[1]-1)*(p[2] - g1[2]))*p[0:3]
        M1[:,3] = M1[:,3] + p[6]*abs((p[0] - g1[0]-1)*(p[1] - g1[1])*(p[2] - g1[2]))*p[0:3]
        M1[:,4] = M1[:,4] + p[6]*abs((p[0] - g1[0])*(p[1] - g1[1])*(p[2] - g1[2]-1))*p[0:3]
        M1[:,5] = M1[:,5] + p[6]*abs((p[0] - g1[0])*(p[1] - g1[1]-1)*(p[2] - g1[2]-1))*p[0:3]
        M1[:,6] = M1[:,6] + p[6]*abs((p[0] - g1[0]-1)*(p[1] - g1[1]-1)*(p[2] - g1[2]-1))*p[0:3]
        M1[:,7] = M1[:,7] + p[6]*abs((p[0] - g1[0]-1)*(p[1] - g1[1])*(p[2] - g1[2]-1))*p[0:3]

    for p in L:
        M2[:,:,0] = M2[:,:,0] + p[6]*abs((p[0] - g1[0])*(p[1] - g1[1])*(p[2] - g1[2]))*np.matmul((p[0:3] - M1[:,0]/M0[0]).reshape(3,1), (p[0:3] - M1[:,0]/M0[0]).reshape(1,3))
        M2[:,:,1] = M2[:,:,1] + p[6]*abs((p[0] - g1[0])*(p[1] - g1[1]-1)*(p[2] - g1[2]))*np.matmul((p[0:3] - M1[:,1]/M0[1]).reshape(3,1), (p[0:3] - M1[:,1]/M0[1]).reshape(1,3))
        M2[:,:,2] = M2[:,:,2] + p[6]*abs((p[0] - g1[0]-1)*(p[1] - g1[1]-1)*(p[2] - g1[2]))*np.matmul((p[0:3] - M1[:,2]/M0[2]).reshape(3,1), (p[0:3] - M1[:,2]/M0[2]).reshape(1,3))
        M2[:,:,3] = M2[:,:,3] + p[6]*abs((p[0] - g1[0]-1)*(p[1] - g1[1])*(p[2] - g1[2]))*np.matmul((p[0:3] - M1[:,3]/M0[3]).reshape(3,1), (p[0:3] - M1[:,3]/M0[3]).reshape(1,3))
        M2[:,:,4] = M2[:,:,4] + p[6]*abs((p[0] - g1[0])*(p[1] - g1[1])*(p[2] - g1[2]-1))*np.matmul((p[0:3] - M1[:,4]/M0[4]).reshape(3,1), (p[0:3] - M1[:,4]/M0[4]).reshape(1,3))
        M2[:,:,5] = M2[:,:,5] + p[6]*abs((p[0] - g1[0])*(p[1] - g1[1]-1)*(p[2] - g1[2]-1))*np.matmul((p[0:3] - M1[:,5]/M0[5]).reshape(3,1), (p[0:3] - M1[:,5]/M0[5]).reshape(1,3))
        M2[:,:,6] = M2[:,:,6] + p[6]*abs((p[0] - g1[0]-1)*(p[1] - g1[1]-1)*(p[2] - g1[2]-1))*np.matmul((p[0:3] - M1[:,6]/M0[6]).reshape(3,1), (p[0:3] - M1[:,6]/M0[6]).reshape(1,3))
        M2[:,:,7] = M2[:,:,7] + p[6]*abs((p[0] - g1[0]-1)*(p[1] - g1[1])*(p[2] - g1[2]-1))*np.matmul((p[0:3] - M1[:,7]/M0[7]).reshape(3,1), (p[0:3] - M1[:,7]/M0[7]).reshape(1,3))


    G000 = { 'M0' : M0[0],
             'M1' : M1[:,0],
             'M2' : M2[:,:,0]
           }
    G010 = { 'M0' : M0[1],
             'M1' : M1[:,1],
             'M2' : M2[:,:,1]
           }
    G110 = { 'M0' : M0[2],
             'M1' : M1[:,2],
             'M2' : M2[:,:,2]
           }
    G100 = { 'M0' : M0[3],
             'M1' : M1[:,3],
             'M2' : M2[:,:,3]
           }
    G001 = { 'M0' : M0[4],
             'M1' : M1[:,4],
             'M2' : M2[:,:,4]
           }
    G011 = { 'M0' : M0[5],
             'M1' : M1[:,5],
             'M2' : M2[:,:,5]
           }
    G111 = { 'M0' : M0[6],
             'M1' : M1[:,6],
             'M2' : M2[:,:,6]
           }
    G101 = { 'M0' : M0[7],
             'M1' : M1[:,7],
             'M2' : M2[:,:,7]
           }

    return  G000, G010, G110, G100, G001, G011, G111, G101

def grid_moments_D(LM, merged_list, g1):
    zerothM_list = []
    zerothav_list = []
    zerothm_list = []
    firstM_list = []
    firstav_list = []
    firstm_list = []
    secondM_list = []
    secondav_list = []
    secondm_list = []
    premerge = moments_on_grid(LM, g1)
    counter = 0


    for Lmm in merged_list:
        postmerge = moments_on_grid(Lmm, g1)
        zeroth_moments_D = []
        first_moments_D = []
        second_moments_D = []

        for i in range(0,8):
                zeroth_moments_D.append(abs(premerge[i]['M0'] - postmerge[i]['M0']))
                first_moments_D.append(abs(premerge[i]['M1'] - postmerge[i]['M1']))
                second_moments_D.append(abs(premerge[i]['M2'] - postmerge[i]['M2']))

        zeroth_moments_D = np.array(zeroth_moments_D)
        zerothM = max(zeroth_moments_D)
        zerothav = np.mean(zeroth_moments_D)
        zerothm = min(zeroth_moments_D)
        first_moments_D = np.array(first_moments_D)
        firstM = np.array([max(first_moments_D[:,0]), max(first_moments_D[:,1]), max(first_moments_D[:,2])])
        firstav = np.array([np.mean(first_moments_D[:,0]), np.mean(first_moments_D[:,1]), np.mean(first_moments_D[:,2])])
        firstm = np.array([max(first_moments_D[:,0]), max(first_moments_D[:,1]), max(first_moments_D[:,2])])
        second_moments_D = np.array(second_moments_D)
        secondM1 = np.array([max(second_moments_D[:,0,0]), max(second_moments_D[:,0,1]), max(second_moments_D[:,0,2])])
        secondM2 = np.array([max(second_moments_D[:,1,0]), max(second_moments_D[:,1,1]), max(second_moments_D[:,1,2])])
        secondM3 = np.array([max(second_moments_D[:,2,0]), max(second_moments_D[:,2,1]), max(second_moments_D[:,2,2])])
        secondM = np.array([secondM1, secondM2, secondM3])
        secondav1 = np.array([np.mean(second_moments_D[:,0,0]), np.mean(second_moments_D[:,0,1]), np.mean(second_moments_D[:,0,2])])
        secondav2 = np.array([np.mean(second_moments_D[:,1,0]), np.mean(second_moments_D[:,1,1]), np.mean(second_moments_D[:,1,2])])
        secondav3 = np.array([np.mean(second_moments_D[:,2,0]), np.mean(second_moments_D[:,2,1]), np.mean(second_moments_D[:,2,2])])
        secondav = np.array([secondav1, secondav2, secondav3])
        secondm1 = np.array([max(second_moments_D[:,0,0]), max(second_moments_D[:,0,1]), max(second_moments_D[:,0,2])])
        secondm2 = np.array([max(second_moments_D[:,1,0]), max(second_moments_D[:,1,1]), max(second_moments_D[:,1,2])])
        secondm3 = np.array([max(second_moments_D[:,2,0]), max(second_moments_D[:,2,1]), max(second_moments_D[:,2,2])])
        secondm = np.array([secondm1, secondm2, secondm3])

        zerothM_list.append(zerothM)
        zerothm_list.append(zerothm)
        firstM_list.append(firstM)
        firstm_list.append(firstm)
        secondM_list.append(secondM)
        secondm_list.append(secondm)
        zerothav_list.append(zerothav)
        firstav_list.append(firstav)
        secondav_list.append(secondav)


    minimums = {'least0Max' : zerothM_list.index(min(zerothM_list)) + 1,
                'least0min' : zerothm_list.index(min(zerothm_list)) + 1,
                'least0av' : zerothav_list.index(min(zerothav_list)) + 1,
                'least1Maxx' : list(np.array(firstM_list)[:,0]).index(min(np.array(firstM_list)[:,0])) + 1,
                'least1Maxy' : list(np.array(firstM_list)[:,1]).index(min(np.array(firstM_list)[:,1])) + 1,
                'least1Maxz' : list(np.array(firstM_list)[:,2]).index(min(np.array(firstM_list)[:,2])) + 1,
                'least1minx' : list(np.array(firstm_list)[:,0]).index(min(np.array(firstm_list)[:,0])) + 1,
                'least1miny' : list(np.array(firstm_list)[:,1]).index(min(np.array(firstm_list)[:,1])) + 1,
                'least1minz' : list(np.array(firstm_list)[:,2]).index(min(np.array(firstm_list)[:,2])) + 1,
                'least1avx' : list(np.array(firstav_list)[:,0]).index(min(np.array(firstav_list)[:,0])) + 1,
                'least1avy' : list(np.array(firstav_list)[:,1]).index(min(np.array(firstav_list)[:,1])) + 1,
                'least1avz' : list(np.array(firstav_list)[:,2]).index(min(np.array(firstav_list)[:,2])) + 1,
                'least2Maxxx' : list(np.array(secondM_list)[:,0,0]).index(min(np.array(secondM_list)[:,0,0])) + 1,
                'least2Maxxy' : list(np.array(secondM_list)[:,1,0]).index(min(np.array(secondM_list)[:,1,0])) + 1,
                'least2Maxxz' : list(np.array(secondM_list)[:,2,0]).index(min(np.array(secondM_list)[:,2,0])) + 1,
                'least2Maxyx' : list(np.array(secondM_list)[:,0,1]).index(min(np.array(secondM_list)[:,0,1])) + 1,
                'least2Maxyy' : list(np.array(secondM_list)[:,1,1]).index(min(np.array(secondM_list)[:,1,1])) + 1,
                'least2Maxyz' : list(np.array(secondM_list)[:,2,1]).index(min(np.array(secondM_list)[:,2,1])) + 1,
                'least2Maxzx' : list(np.array(secondM_list)[:,2,0]).index(min(np.array(secondM_list)[:,2,0])) + 1,
                'least2Maxzy' : list(np.array(secondM_list)[:,2,1]).index(min(np.array(secondM_list)[:,2,1])) + 1,
                'least2Maxzz' : list(np.array(secondM_list)[:,2,2]).index(min(np.array(secondM_list)[:,2,2])) + 1,
                'least2minxx' : list(np.array(secondm_list)[:,0,0]).index(min(np.array(secondm_list)[:,0,0])) + 1,
                'least2minxy' : list(np.array(secondm_list)[:,1,0]).index(min(np.array(secondm_list)[:,1,0])) + 1,
                'least2minxz' : list(np.array(secondm_list)[:,2,0]).index(min(np.array(secondm_list)[:,2,0])) + 1,
                'least2minyx' : list(np.array(secondm_list)[:,0,1]).index(min(np.array(secondm_list)[:,0,1])) + 1,
                'least2minyy' : list(np.array(secondm_list)[:,1,1]).index(min(np.array(secondm_list)[:,1,1])) + 1,
                'least2minyz' : list(np.array(secondm_list)[:,2,1]).index(min(np.array(secondm_list)[:,2,1])) + 1,
                'least2minzx' : list(np.array(secondm_list)[:,2,0]).index(min(np.array(secondm_list)[:,2,0])) + 1,
                'least2minzy' : list(np.array(secondm_list)[:,2,1]).index(min(np.array(secondm_list)[:,2,1])) + 1,
                'least2minzz' : list(np.array(secondm_list)[:,2,2]).index(min(np.array(secondm_list)[:,2,2])) + 1,
                'least2avxx' : list(np.array(secondav_list)[:,0,0]).index(min(np.array(secondav_list)[:,0,0])) + 1,
                'least2avxy' : list(np.array(secondav_list)[:,1,0]).index(min(np.array(secondav_list)[:,1,0])) + 1,
                'least2avxz' : list(np.array(secondav_list)[:,2,0]).index(min(np.array(secondav_list)[:,2,0])) + 1,
                'least2avyx' : list(np.array(secondav_list)[:,0,1]).index(min(np.array(secondav_list)[:,0,1])) + 1,
                'least2avyy' : list(np.array(secondav_list)[:,1,1]).index(min(np.array(secondav_list)[:,1,1])) + 1,
                'least2avyz' : list(np.array(secondav_list)[:,2,1]).index(min(np.array(secondav_list)[:,2,1])) + 1,
                'least2avzx' : list(np.array(secondav_list)[:,2,0]).index(min(np.array(secondav_list)[:,2,0])) + 1,
                'least2avzy' : list(np.array(secondav_list)[:,2,1]).index(min(np.array(secondav_list)[:,2,1])) + 1,
                'least2avzz' : list(np.array(secondav_list)[:,2,2]).index(min(np.array(secondav_list)[:,2,2])) + 1
                }

    return minimums, zerothM_list, zerothm_list, zerothav_list, firstM_list, firstm_list, firstav_list, secondm_list, secondav_list


grid_D1 = grid_moments_D(LM, merged_list, (0,0,0))

In [ ]:
least0Max = []
least0min = []
least0av = []
least1Maxx = []
least1Maxy = []
least1Maxz = []
least1minx = []
least1miny = []
least1minz = []
least1avx = []
least1avy = []
least1avz = []
least2Maxxx = []
least2Maxxy = []
least2Maxxz = []
least2Maxyx = []
least2Maxyy = []
least2Maxyz = []
least2Maxzx = []
least2Maxzy = []
least2Maxzz = []
least2minxx = []
least2minxy = []
least2minxz = []
least2minyx = []
least2minyy = []
least2minyz = []
least2minzx = []
least2minzy = []
least2minzz = []
least2avxx = []
least2avxy = []
least2avxz = []
least2avyx = []
least2avyy = []
least2avyz = []
least2avzx = []
least2avzy = []
least2avzz = []

difference_pos_list = [least0min, least0av, least1Maxx, least1Maxy, least1Maxz, least1minx,
                       least1miny, least1minz, least1avx, least1avy, least1avz, least2Maxxx,
                       least2Maxxy, least2Maxxz, least2Maxyx, least2Maxyy, least2Maxyz,
                       least2Maxzx, least2Maxzy, least2Maxzz, least2minxx, least2minxy,
                       least2minxz, least2minyx, least2minyy, least2minyz, least2minzx,
                       least2minzy, least2minzz, least2avxx, least2avxy, least2avxz, least2avyx,
                       least2avyy, least2avyz, least2avzx, least2avzy, least2avzz]

for j in range(0,100):
    LM = ran_cells_M(1, 104, 0, 1, (0,0,0))[0]
    LMmerg_pos1 = merger1(LM, 100, (0,0,0), 1)
    LMmerg_pos2 = merger1(LM, 100, (0,0,0), 2)
    LMmerg_pos3 = merger1(LM, 100, (0,0,0), 3)
    LMmerg_pos4 = merger1(LM, 100, (0,0,0), 4)
    LMmerg_pos5 = merger1(LM, 100, (0,0,0), 5)
    LMmerg_pos6 = merger1(LM, 100, (0,0,0), 6)
    merged_list = (LMmerg_pos1, LMmerg_pos2, LMmerg_pos3, LMmerg_pos4, LMmerg_pos5, LMmerg_pos6)
    Diff_grid = grid_moments_D(LM, merged_list, (0,0,0))[0]
    least0Max.append(Diff_grid['least0Max'])
    least0min.append(Diff_grid['least0min'])
    least0av.append(Diff_grid['least0av'])
    least1Maxx.append(Diff_grid['least1Maxx'])
    least1Maxy.append(Diff_grid['least1Maxy'])
    least1Maxz.append(Diff_grid['least1Maxz'])
    least1minx.append(Diff_grid['least1minx'])
    least1miny.append(Diff_grid['least1miny'])
    least1minz.append(Diff_grid['least1minz'])
    least1avx.append(Diff_grid['least1avx'])
    least1avy.append(Diff_grid['least1avy'])
    least1avz.append(Diff_grid['least1avx'])
    least2Maxxx.append(Diff_grid['least2Maxxx'])
    least2Maxxy.append(Diff_grid['least2Maxxy'])
    least2Maxxz.append(Diff_grid['least2Maxxz'])
    least2Maxyx.append(Diff_grid['least2Maxyx'])
    least2Maxyy.append(Diff_grid['least2Maxyy'])
    least2Maxyz.append(Diff_grid['least2Maxyz'])
    least2Maxzx.append(Diff_grid['least2Maxzx'])
    least2Maxzy.append(Diff_grid['least2Maxzy'])
    least2Maxzz.append(Diff_grid['least2Maxzz'])
    least2minxx.append(Diff_grid['least2minxx'])
    least2minxy.append(Diff_grid['least2minxy'])
    least2minxz.append(Diff_grid['least2minxz'])
    least2minyx.append(Diff_grid['least2minyx'])
    least2minyy.append(Diff_grid['least2minyy'])
    least2minyz.append(Diff_grid['least2minyz'])
    least2minzx.append(Diff_grid['least2minzx'])
    least2minzy.append(Diff_grid['least2minzy'])
    least2minzz.append(Diff_grid['least2minzz'])
    least2avxx.append(Diff_grid['least2avxx'])
    least2avxy.append(Diff_grid['least2avxy'])
    least2avxz.append(Diff_grid['least2avxz'])
    least2avyx.append(Diff_grid['least2avyx'])
    least2avyy.append(Diff_grid['least2avyy'])
    least2avyz.append(Diff_grid['least2avyz'])
    least2avzx.append(Diff_grid['least2avzx'])
    least2avzy.append(Diff_grid['least2avzy'])
    least2avzz.append(Diff_grid['least2avzz'])


pos1_perc = []
pos2_perc = []
pos3_perc = []
pos4_perc = []
pos5_perc = []
pos6_perc = []

for k in difference_pos_list:
    count1 = 0
    count2 = 0
    count3 = 0
    count4 = 0
    count5 = 0
    count6 = 0
    for n in k:
        if n == 1:
            count1 = count1 + 1
        elif n == 2:
            count2 = count2 + 1
        elif n == 3:
            count3 = count3 + 1
        elif n == 4:
            count4 = count4 + 1
        elif n == 5:
            count5 = count5 + 1
        elif n == 6:
            count6 = count6 + 1
    pos1_perc.append(count1/len(k))
    pos2_perc.append(count2/len(k))
    pos3_perc.append(count3/len(k))
    pos4_perc.append(count4/len(k))
    pos5_perc.append(count5/len(k))
    pos6_perc.append(count6/len(k))

TypeError: list indices must be integers or slices, not tuple

In [ ]:
print(f'pos1 {pos1_perc}')
print(f'pos2 {pos2_perc}')
print(f'pos3 {pos3_perc}')
print(f'pos4 {pos4_perc}')
print(f'pos5 {pos5_perc}')
print(f'pos6 {pos6_perc}')

In [ ]:
def continuous_moments_3uniform(n,lx,ux,ly,uy,lz,uz):
    '''
    f - istribution function
    n - number of particles per cell (weights assumed to be from U(0,1)
    note :  space distribution assumed to be uniform
    lx - lower bound x
    ux - uppper bound x
    ly - lower bound y
    uy - uppper bound y
    lz - lower bound z
    uz - uppper bound z
    '''
    fx = lambda v : 1/(ux - lx)
    fy = lambda v : 1/(uy - ly)
    fz = lambda v : 1/(uz - lz)

    moment0 = (inte.quad(fx, lx, ux)[0]*inte.quad(fy, ly, uy)[0]*inte.quad(fz, lz, uz)[0])*n/2

    fx1 = lambda v : fx(v)*v
    fy1 = lambda v : fy(v)*v
    fz1 = lambda v : fz(v)*v

    fxx2 = lambda v : fx(v)*(v-(moment1_x/moment0))**2
    fyy2 = lambda v : fy(v)*(v-(moment1_y/moment0))**2
    fzz2 = lambda v : fz(v)*(v-(moment1_z/moment0))**2
    fx2 = lambda v : fx(v)*(v-(moment1_x/moment0))
    fy2 = lambda v : fy(v)*(v-(moment1_y/moment0))
    fz2 = lambda v : fz(v)*(v-(moment1_z/moment0))

    moment1_x = (inte.quad(fx1, lx, ux)[0]*(inte.quad(fy, ly, uy)[0]*(inte.quad(fz, lz, uz)[0])))*n/2
    moment1_y = (inte.quad(fx, lx, ux)[0]*(inte.quad(fy1, ly, uy)[0]*(inte.quad(fz, lz, uz)[0])))*n/2
    moment1_z = (inte.quad(fx, lx, ux)[0]*(inte.quad(fy, ly, uy)[0]*(inte.quad(fz1, lz, uz)[0])))*n/2

    moment1 = np.array([moment1_x, moment1_y, moment1_z])

    moment2xx = (inte.quad(fxx2, lx, ux)[0]*(inte.quad(fy, ly, uy)[0]*(inte.quad(fz, lz, uz)[0])))*n/2
    moment2yy = (inte.quad(fyy2, ly, uy)[0]*(inte.quad(fx, lx, ux)[0]*(inte.quad(fz, lz, uz)[0])))*n/2
    moment2zz = (inte.quad(fzz2, lz, uz)[0]*(inte.quad(fx, lx, ux)[0]*(inte.quad(fz, lz, uz)[0])))*n/2

    moment2xy = (inte.quad(fx2, lx, ux)[0]*(inte.quad(fy2, ly, uy)[0]*(inte.quad(fz, lz, uz)[0])))*n/2
    moment2xz = (inte.quad(fx2, lx, ux)[0]*(inte.quad(fy, ly, uy)[0]*(inte.quad(fz2, lz, uz)[0])))*n/2
    moment2yz = (inte.quad(fx, lx, ux)[0]*(inte.quad(fy2, ly, uy)[0]*(inte.quad(fz2, lz, uz)[0])))*n/2
    moment2yx = moment2xy
    moment2zx = moment2xz
    moment2zy = moment2yz

    moment2 = np.array([(moment2xx,moment2xy,moment2xz),(moment2yx,moment2yy,moment2yz),(moment2zx,moment2zy,moment2zz)])

    return moment0, moment1, moment2

In [ ]:
cells_3U = ran_cells_3U(100, 100, 0, 0.1, 0, 10, 0, 1000, (0,0,0))
uni3_M0, uni3_M1, uni3_M2, uni3_M3 = moments_calc(cells_3U)

c_uni3_M0, c_uni3_M1, c_uni3_M2 = continuous_moments_3uniform(100, 0, 0.1, 0, 10, 0, 1000)

N1uni3_m0_D = 2*(c_uni3_M0 - uni3_M0['mean'])/(c_uni3_M0 + uni3_M0['mean'])
N1uni3_m1_D = 2*(c_uni3_M1 - uni3_M1['mean'])/(c_uni3_M1 + uni3_M1['mean'])
N1uni3_m2_D = 2*(c_uni3_M2 - uni3_M2['mean'])/(c_uni3_M2 + uni3_M2['mean'])

N2uni3_m0_D = 2*(c_uni3_M0 - uni3_M0['mean'])/(uni3_M0['st_dev'])
N2uni3_m1_D = 2*(c_uni3_M1 - uni3_M1['mean'])/(np.mean(uni3_M1['st_dev']))
N2uni3_m2_D = 2*(c_uni3_M2 - uni3_M2['mean'])/(np.mean(uni3_M2['st_dev']))

uni3_m0_D = (c_uni3_M0 - uni3_M0['mean'])
uni3_m1_D = (c_uni3_M1 - uni3_M1['mean'])
uni3_m2_D = (c_uni3_M2 - uni3_M2['mean'])

uni3_m0_D, uni3_m1_D, uni3_m2_D, N1uni3_m0_D, N1uni3_m1_D, N1uni3_m2_D, N2uni3_m0_D, N2uni3_m1_D, N2uni3_m2_D


In [ ]:
c_uni3_M0, c_uni3_M1, c_uni3_M2, uni3_M0['mean'], uni3_M1['mean'], uni3_M2['mean']

In [ ]:
#splitting particles

def heaviest_particle(L):
    heaviest = L[0]
    for p in L:
        if p[6] > heaviest[6]:
            heaviest = p
    return heaviest

def splitter1(L, k, g1, pos):
    '''
    L - set of pqrticles to be merged
    k - desired number of particles
    g1 - smallest grid angle (i.e. the angle of the grid with lowest added coordinates value)
    '''
    L = list(L)
    s = len(L)

    while len(L) < k:
        p1 = np.zeros(7)
        p2 = np.zeros(7)
        p1_r = np.zeros(7)
        p2_r = np.zeros(7)
        score_r = 1000

        particle = heaviest_particle(L)

        w = particle[6]
        vx = particle[3]
        vy = particle[4]
        vz = particle[5]

        aux = w*vx
        auy = w*vy
        auz = w*vz
        aPxx = w*(vx - aux)*(vx - aux)
        aPxy = w*(vx - aux)*(vy - auy)
        aPxz = w*(vx - aux)*(vz - auz)
        aPyz = w*(vz - auz)*(vy - auy)
        aPzz = w*(vz - auz)*(vz - auz)
        aPyy = w*(vy - auy)*(vy - auy)
        ap = np.random.uniform(0,1)

        for sol in solutions2:
            score = 0
            p1[6] = sol[0].subs([(n,w),(p,ap)])
            p2[6] = sol[1].subs([(n,w),(p,ap)])
            p1[3] = sol[2].subs([(n,w),(p,ap),(ux, aux), (Pxx, aPxx)])
            p1[4] = sol[3].subs([(n,w),(p,ap),(uy, auy), (Pyy, aPyy)])
            p1[5] = sol[4].subs([(n,w),(p,ap),(uz, auz), (Pzz, aPzz)])
            p2[3] = sol[5].subs([(n,w),(p,ap),(ux, aux), (Pxx, aPxx)])
            p2[4] = sol[6].subs([(n,w),(p,ap),(uy, auy), (Pyy, aPyy)])
            p2[5] = sol[7].subs([(n,w),(p,ap),(uz, auz), (Pzz, aPzz)])

            if abs(p1[3] + aux) != abs(p1[3]) + abs(aux):
                score = score + 1
                if abs(p1[3] + aux) >= abs(p1_r[3] + aux):
                    score = score + 1
            if abs(p1[4] + auy) != abs(p1[4]) + abs(auy):
                score = score + 1
                if abs(p1[4] + auy) >= abs(p1_r[4] + auy):
                    score = score + 1
            if abs(p1[5] + auz) != abs(p1[5]) + abs(auz):
                score = score + 1
                if abs(p1[6] + auz) >= abs(p1_r[6] + auz):
                    score = score + 1
            if abs(p2[3] + aux) != abs(p2[3]) + abs(aux):
                score = score + 1
                if abs(p2[3] + aux) >= abs(p2_r[3] + aux):
                    score = score + 1
            if abs(p2[4] + auy) != abs(p2[4]) + abs(auy):
                score = score + 1
                if abs(p2[4] + auy) >= abs(p2_r[4] + auy):
                    score = score + 1
            if abs(p2[5] + auz) != abs(p2[5]) + abs(auz):
                score = score + 1
                if abs(p2[6] + auz) >= abs(p2_r[6] + auz):
                    score = score + 1

            if score_r > score:
                p1_r = p1
                p2_r = p2
                score_r = score

        if pos == 1:
            p1_r[0:3] = particle[0:3]
            p2_r[0:3] = particle[0:3]

        L = [el for el in L if not np.array_equal(el, particle)]
        L.append(p1_r)
        L.append(p2_r)

        print(f'changes iteration {abs(s - len(L))}')
        print('before')
        print(particle)
        print('after')
        print(p1_r, p2_r)



    return np.array(L)

In [ ]:
LMless = ran_cells_M(1, 96, 0, 1, (0,0,0))[0]
LMmerg_pos1 = splitter1(LMless, 100, (0,0,0), 1)
#LMmerg_pos2 = splitter1(LM, 100, (0,0,0), 2)
#LMmerg_pos3 = splitter1(LM, 100, (0,0,0), 3)
#LMmerg_pos4 = splitter1(LM, 100, (0,0,0), 4)
#LMmerg_pos5 = splitter1(LM, 100, (0,0,0), 5)
#LMmerg_pos6 = splitter1(LM, 100, (0,0,0), 6)
split_list = [LMmerg_pos1]

grid_moments_D(LMless, split_list, (0,0,0))